vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        product_thumbnail:
            uri_prefix: /images/products/thumbnails
            upload_destination: "%kernel.project_dir%/public/images/products/thumbnails"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        product_image:
            uri_prefix: /images/products/images
            upload_destination: "%kernel.project_dir%/public/images/products/images"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        category_thumbnail:
            uri_prefix: /images/categories
            upload_destination: "%kernel.project_dir%/public/images/categories"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        brand_logos:
            uri_prefix: /uploads/logo_images
            upload_destination: "%kernel.project_dir%/public/uploads/logo_images"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
